"""Cluster analysis CSV export for batch verification results (SV-FR-36).

Pure serialization of an already-computed batch analysis result the client
holds (`batchResult` in BatchAnalysisPanel.tsx) into a downloadable CSV. No
model inference, no recomputed embeddings/similarity/clustering happens
here. Every metadata value written to the file (model identity, both
thresholds, all three version strings) is derived server-side from the
validated `model` key alone -- the client never supplies a threshold or
version value, so a tampered payload cannot misrepresent the
evidence-vs-threshold framing MQ-10 requires the file to state honestly.
"""

from __future__ import annotations

import csv
import io
import re
from datetime import datetime
from typing import Sequence

from pydantic import BaseModel

from .clustering import ClusteringSpec
from .service import SpeakerModelSpec

MIN_BATCH_SIZE = 2
MAX_BATCH_SIZE = 100

# The only four opaque-id shapes this system ever produces (demo dataset,
# custom dataset, batch upload, session asset). No shared validator exists
# elsewhere in the codebase for this union -- see dataset.py, custom_recordings.py,
# session_assets.py, and the /batch/upload handler in router.py.
RECORDING_ID_PATTERN = re.compile(
    r"^(rec_[0-9a-f]{16}|crec_[0-9a-f]{64}|upload-\d{3}|asset_[0-9a-f]{32})$"
)

# Cluster ids are generated by clustering.remap_labels_by_first_appearance
# as cluster-1, cluster-2, ... (no leading zeros, starting at 1).
CLUSTER_ID_PATTERN = re.compile(r"^cluster-[1-9][0-9]*$")

# No legitimate opaque id or cluster id begins with any of these -- checked
# explicitly (not just implied by the regexes above) as defense-in-depth
# against CSV formula injection in the spreadsheet application that opens
# the exported file.
_FORMULA_LEAD_CHARS = ("=", "+", "-", "@", "\t", "\r")

_FLOAT_PRECISION = 4


class ExportValidationError(ValueError):
    """Raised when a client-submitted export payload fails validation."""


class ExportClusterSummary(BaseModel):
    cluster_id: str
    member_count: int
    member_indices: list[int]
    member_labels: list[str]
    mean_intra_cluster_similarity: float | None
    min_intra_cluster_similarity: float | None
    representative_index: int
    representative_label: str
    mean_fit_score: float


class ExportRecordingClusterStats(BaseModel):
    cluster_id: str
    mean_similarity_to_cluster: float | None
    min_similarity_to_cluster: float | None
    nearest_index: int
    nearest_label: str
    nearest_similarity: float
    nearest_in_same_cluster: bool


class BatchExportRequest(BaseModel):
    model: str
    labels: list[str]
    cluster_labels: list[str]
    cluster_summaries: list[ExportClusterSummary]
    recording_cluster_stats: list[ExportRecordingClusterStats]
    cluster_count: int


def _validate_label(value: str) -> None:
    if value.startswith(_FORMULA_LEAD_CHARS):
        raise ExportValidationError(f"Invalid recording id: {value!r}.")
    if not RECORDING_ID_PATTERN.match(value):
        raise ExportValidationError(f"Invalid recording id format: {value!r}.")


def _validate_cluster_id(value: str) -> None:
    if not CLUSTER_ID_PATTERN.match(value):
        raise ExportValidationError(f"Invalid cluster id format: {value!r}.")


def validate_export_payload(payload: BatchExportRequest) -> None:
    """Validate a client-submitted export payload (SEC-2).

    Assumes `payload.model` has already been resolved via `get_model_spec`
    by the caller -- this function only validates the shape and content of
    the labels/clustering data, matching this router's existing separation
    between model-key validation and request-body validation.
    """

    labels = payload.labels
    if not MIN_BATCH_SIZE <= len(labels) <= MAX_BATCH_SIZE:
        raise ExportValidationError(
            f"Provide between {MIN_BATCH_SIZE} and {MAX_BATCH_SIZE} labels."
        )
    if len(payload.cluster_labels) != len(labels):
        raise ExportValidationError("cluster_labels must have the same length as labels.")
    if len(payload.recording_cluster_stats) != len(labels):
        raise ExportValidationError(
            "recording_cluster_stats must have the same length as labels."
        )

    summary_ids = [summary.cluster_id for summary in payload.cluster_summaries]
    if len(set(summary_ids)) != len(summary_ids):
        raise ExportValidationError("Duplicate cluster_id in cluster_summaries.")
    if payload.cluster_count != len(payload.cluster_summaries):
        raise ExportValidationError(
            "cluster_count must equal the number of cluster_summaries entries."
        )

    for label in labels:
        _validate_label(label)
    for summary in payload.cluster_summaries:
        _validate_cluster_id(summary.cluster_id)
        for member_label in summary.member_labels:
            _validate_label(member_label)
        _validate_label(summary.representative_label)
    for cluster_id in payload.cluster_labels:
        _validate_cluster_id(cluster_id)
    for stats in payload.recording_cluster_stats:
        _validate_cluster_id(stats.cluster_id)
        _validate_label(stats.nearest_label)

    known_cluster_ids = set(summary_ids)
    for cluster_id in payload.cluster_labels:
        if cluster_id not in known_cluster_ids:
            raise ExportValidationError(
                f"cluster_labels references unknown cluster_id {cluster_id!r}."
            )
    for stats in payload.recording_cluster_stats:
        if stats.cluster_id not in known_cluster_ids:
            raise ExportValidationError(
                f"recording_cluster_stats references unknown cluster_id {stats.cluster_id!r}."
            )


def _fmt(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return f"{value:.{_FLOAT_PRECISION}f}"
    return str(value)


def build_export_csv(
    payload: BatchExportRequest,
    spec: SpeakerModelSpec,
    clustering_spec: ClusteringSpec,
    *,
    pair_threshold_version: str,
    clustering_threshold_version: str,
    preprocessing_version: str,
    generated_at: datetime,
) -> str:
    """Render a validated export payload as a two-section CSV.

    Caller must have already called `validate_export_payload` -- this
    function assumes every cluster_id referenced from `cluster_labels`/
    `recording_cluster_stats` exists in `cluster_summaries`.
    """

    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\r\n")

    metadata: Sequence[tuple[str, object]] = (
        ("model_key", spec.key),
        ("model_label", spec.label),
        ("model_id", spec.model_id),
        ("model_revision", spec.revision),
        ("architecture", spec.architecture),
        ("embedding_dimension", spec.embedding_dimension),
        ("pair_verification_threshold", spec.threshold),
        ("pair_threshold_version", pair_threshold_version),
        ("clustering_distance_threshold", clustering_spec.distance_threshold),
        ("clustering_threshold_version", clustering_threshold_version),
        ("clustering_linkage", clustering_spec.linkage),
        ("distance_metric", "cosine"),
        ("preprocessing_version", preprocessing_version),
        ("recording_count", len(payload.labels)),
        ("cluster_count", len(payload.cluster_summaries)),
        ("export_timestamp_utc", generated_at.strftime("%Y-%m-%dT%H:%M:%SZ")),
    )
    for key, value in metadata:
        writer.writerow([f"# {key}", _fmt(value)])
    writer.writerow(
        [
            "# disclaimer",
            "Similarity scores are evidence to be weighed against the stated "
            "threshold, not proof of speaker identity. Cluster labels (e.g. "
            "cluster-1) are anonymous groupings only and do not represent "
            "verified real-world identities.",
        ]
    )
    writer.writerow([])

    summaries_by_id = {summary.cluster_id: summary for summary in payload.cluster_summaries}

    writer.writerow(
        [
            "label",
            "cluster_id",
            "cluster_size",
            "is_representative",
            "mean_similarity_to_cluster",
            "min_similarity_to_cluster",
            "nearest_label",
            "nearest_similarity",
            "nearest_in_same_cluster",
        ]
    )
    for index, label in enumerate(payload.labels):
        cluster_id = payload.cluster_labels[index]
        summary = summaries_by_id[cluster_id]
        stats = payload.recording_cluster_stats[index]
        writer.writerow(
            [
                _fmt(label),
                _fmt(cluster_id),
                _fmt(summary.member_count),
                _fmt(summary.representative_index == index),
                _fmt(stats.mean_similarity_to_cluster),
                _fmt(stats.min_similarity_to_cluster),
                _fmt(stats.nearest_label),
                _fmt(stats.nearest_similarity),
                _fmt(stats.nearest_in_same_cluster),
            ]
        )

    return buffer.getvalue()
